language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "labadi0"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
  - mvn clean install

services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bankRest;'
  - mysql -u root --default-character-set=utf8 bankRest < scripts/bd.sql
  - mysql -e 'SHOW TABLES FROM bankRest;'

notifications:
  email:
    recipients:
      - mouchakess1230@gmail.com
    on_success: always
    on_failure: always
