language: java
jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "labadi0"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=labadi0_learnTravisCi
  #- mvn clean install
  #- mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',').projectKey=labadi0_learnTravisCi
  - mvn clean install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bankRest;'
  - mysql -u root --default-character-set=utf8 bankRest < scripts/bd.sql
  - mysql -e 'SHOW TABLES FROM bankRest;'

notifications:
  webhooks: https://ucergyfr.webhook.office.com/webhookb2/6d50fce8-110e-4aec-9b44-9682736fe040@b8c19512-2aed-471d-a8d1-9b06e7da786a/TravisCI/33d0d3ac872147c28d10108ce474312b/228d3557-0c16-4cf5-890a-70e78465434b
  #email:
  #recipients:
  #- mouchakess1230@gmail.com
  #on_success: always
  #on_failure: always
