language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "labadi0"
    token:
      secure: "qE3k/rWqxs5yuw+yrpE+eX7EtBnRfJb69mkQ3NK4uZZu5VzzR1g4nlxuXVmJYRQtKgn58Yv0BX+T6MWny3udQMgf8Gb3wLr8tJZT4u0PbuNEYC6Tot1eTNP/Dv4sWs1w7gvBLaYVnWGrVjRy87M/fw/PuUMmx1HZQ54TIBT5b5jtnQqFgeeSSDiCVvBcBZ/nqVWp4o5zKMV/hnaA0ABQvQUoqozKxAXVnrV4sEbFU0GUe6IMB8cppIFBPeumBNexEunHL8ZQyYe+Eu5bhgXbeJtFjV6xty4ymMTIDUBwLV4QJlELJxczEPImV1mwvNVyuF7qCQvjP0GE9HDuihF1AtA7NkgreOKGGGgr/SOt9oAtyAlPpzIazuvhDGoGcb661KS8qQ1BcUFCQrS5sb6h4bEew5W6L6EGTIjolRym5j+gxmppJFsLLYutCfWinfIF7ZPELqgGsva+cZxgyNjxDLCyAgQPIkjLF+IjoNwcWgSaCbqZ1a03gkTeKUvf0O75Q5DFwpzgE8++6cnqWf4PexfNzy5AYKIbU6zIYA8x+JLIvg93hVGID/WCs3oME0jTeJIEPgT/vFaC14HeaXJnhQ6x/5OHFIDmzOTjXiOaphSDJnlP0Vkx21fvD+EQfUxgCWDgWxf5ZwCB51LUcolOWTCLw7ODdnnwh3mmaCaQ+AM=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi

services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bankRest;'
  - mysql -u root --default-character-set=utf8 bankRest < scripts/bd.sql
  - mysql -e 'SHOW TABLES FROM bankRest;'

notifications:
  email:
    recipients:
      - mouchakess1230@gmail.com
    on_success: always
    on_failure: always
