language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "labadi0"
    token:
      secure: "cOw7EnhCtmWLNHftpX6RRTdb8C9KjUCPbvOWmLgG8t9E1AdFZDX/yJ4dmg0ivI9cloYVvBGZtpJhACozGNIg1Gm6E+kHOlA3IleS+/+wJJtH44ewgBfZxZ938ndZcrQ1l94/FTTLQYBW+9DZabWW3N+zlVjdMTVho19F1yLp5Qp1EdfLT/ACv3vbpow7ohx016GmTTOKX7MAiVC3jlQcaxHRwVjefKURP/rvemYvdtAOfsisBKthcb6lTAMXNEYNZj7uPwoBcM0obiISBRJ9AJzYJRERKBXXHpIbCsW8Co2f4l1cBJC0sKVNgo8noxsiIyvaxGPxUAQBcOzjETWWcS9g1I/QNAcSx3yvjhVYgq6Y80R8bAQmMvQShQxarqTY5SkAVapJnpiJ3uyvHxbbwHTSV1UNA3rX0V6wAMEOKd/uqgfz8v3csaAC3ZVFGd3x+oMlCLgPGyyJ/aOBUjXko8hUFp1a8h4np8biEh2oWw+IPRb3IwimSGHvuW7125tRfdL5daE2HIw3awQJgE2lTOzksZ6Li4+TJ0nFdBfeBpMzRbgHh3CeOWLmBsaVAeUvdpmuPXtQ84PtFfxNgy8Hc761F7X26VVRgrru7iWUmmRSNjwEz1GTEmekGLAV3uUcSVyV4F6PwOGVeJehCfp/GwBw5S/xsUf8Nv5iQLkDfjA="

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage

services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bankRest;'
  - mysql -u root --default-character-set=utf8 bankRest < scripts/bd.sql
  - mysql -e 'SHOW TABLES FROM bankRest;'

notifications:
  email:
    recipients:
      - mouchakess1230@gmail.com
    on_success: always
    on_failure: always
